# This file contains values from Cookiecutter

default_context:
  project_name: "model-converter"
  project_description: "PyTorch model conversion to different formats"
  organization: "OpenCV.AI"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "opencv-ai"
  email: "contact@opencv.ai"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
